# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib yar, .registration = TRUE
NULL

# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_yar_wrappers", use_symbols = TRUE, package_name = "yar")

#' @usage NULL
#' @useDynLib yar, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

# nolint end
